version: 2
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:14.1
    steps:
      - checkout
      - run:
          name: npm install
          command: npm —prefix ./functions install ./functions
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN  --only functions

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master # masterブランチのみ実行
